# Generated by Django 5.0.7 on 2024-11-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epay_app', '0002_alter_orders_quantity_alter_orders_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_price',
            new_name='price',
        ),
    ]
